# Generated by Django 4.0.6 on 2023-01-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
